# Dependencies
gems:
    - mini_magick
    - jekyll-sitemap
    - octopress-paginate
    - jekyll-feed
env: production
markdown:      kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Jeremy Rubin'
tagline:          ''
description:     'Bitcoin research, programming languages, hardware, and applied cryptography.'
url:            https://rubin.io
locale:         en_US
og_image:       /public/img/jeremy3.jpg

keep_files: [public, .git]

author:
  name:           'Jeremy Rubin'
  twitter:            https://twitter.com/JeremyRubin
  resume:         /public/pdfs/resume.pdf

pagination:
    title_suffix: " (page :num)"


# Custom vars
version:          4.2.0
lsi: false
collections:
  projects:
      output: true
      permalink: /projects/:path/
  talks:
      output: true
      permalink: /talks/:path/
